version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: image/go/1.17.8.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../..:/app
    depends_on:
      - postgresql
    environment:
      GOMAPSROOT: ${GOMAPSROOT}
    command: go run cmd/main/main.go
  postgresql:
    build:
      context: .
      dockerfile: image/postgresql/14.2.dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
